apiVersion: v1
kind: Service
metadata:
  name: cicd-app-service
spec:
  type: NodePort
  selector:
    app: cicd-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
